---
title: "BMFrog Analysis"
output: html_document
date: "2024-03-07"
---

```{r setup}
library(tidyverse)
library(sf)
library(mapview)
library(terra)
library(readr)
library(readxl)
library(cmdstanr)
library(bayesplot)
library(httr)
check_cmdstan_toolchain(fix = TRUE, quiet = TRUE)
options(mc.cores=4)
register_knitr_engine(override = FALSE)
```

# Load Site Data  

```{r}
site_metadata <- read_excel("data/TLM_Barmah-Millewa_2022-23_AM_deployment_metadata.xlsx")
site_metadata_sf <- site_metadata %>% 
  st_as_sf(coords = c("Easting", "Northing"), crs = 28355) %>%
  mutate(`Site name` = case_when(`Site name` == "Warri" ~ "Warri Yards", 
                                 TRUE ~ `Site name`), 
         Site = paste(`Site name`, AM_no, sep = "_AM"), 
         No_survey_nights = as.numeric(No_survey_nights)) %>%
  arrange(`Site`) %>%
  filter(!is.na(No_survey_nights) & No_survey_nights > 0)

#nights deployed 
nights_dep <- list()
for(i in 1:nrow(site_metadata_sf)) {
  nights_dep[[i]] <- data.frame(Site = site_metadata_sf$Site[i], 
                           Date = seq.Date(from = as.Date(site_metadata_sf$Date_deployed[i]), 
                                           by = "1 day", 
                                           length.out = site_metadata_sf$No_survey_nights[i]))
}
nights_dep_joined <- bind_rows(nights_dep)
```

```{r}
site_hull <- st_convex_hull(site_metadata_sf %>% st_combine()) %>% 
  st_transform(3577) %>%
  st_buffer(5000)
hydro_data <- vicmap_query("open-data-platform:hy_water_area_polygon") %>%
  filter(BBOX(site_hull)) %>%
  collect()

mapview(hydro_data, zcol = "feature_type_code") + mapview(site_metadata_sf)

sf::st_write(site_hull, "data/barmah_hull/barmah_hull.shp")
sf::st_write(site_metadata_sf %>% st_transform(3577) %>% st_buffer(100), "data/site_metadata_sf/site_metadata_sf.shp", overwrite = T)
```
```{r hydro}
# load in csv files of hydro conditions 
list.files("https://github.com/JustinCally/dea-barmah/tree/main/output")
req <- GET("https://api.github.com/repos/JustinCally/dea-barmah/git/trees/main?recursive=1")
stop_for_status(req)
filelist <- unlist(lapply(content(req)$tree, "[", "path"), use.names = F)
csv_files <- paste0("https://raw.githubusercontent.com/JustinCally/dea-barmah/main/",
                         grep("output/", filelist, value = TRUE, fixed = TRUE))
csv_files <- grep(".ipynb_checkpoints")

sapply(function_files, source, verbose = F)

#paste
csv_files <- paste0("https://raw.githubusercontent.com/JustinCally/dea-barmah/main/output/", site_metadata_sf$Site, ".csv")
csv_files <- stringr::str_replace_all(csv_files, pattern = " ", replacement = "%20")
hydryo_data <- list()
for(i in 1:length(csv_files)) {
  hydryo_data[[i]] <- readr::read_csv(csv_files[i]) %>%
    mutate(Site = site_metadata_sf$Site[i])
}

hydro_data_combined <- bind_rows(hydryo_data)
```

```{r interpolation}
#hydro interpolation 

new_df_raw <- data.frame(date = seq(from = min(hydryo_data_combined$date),
                                to = max(hydryo_data_combined$date),
                                by="day"))

interpolate_data <- list()

for(i in 1:length(csv_files)) {
  
  hd <- hydryo_data[[i]]
  
  mod_pv <- loess(pv ~ as.numeric(date), data = hd, span = 0.075)
  mod_npv <- loess(npv ~ as.numeric(date), data = hd, span = 0.075)
  mod_bs <- loess(bs ~ as.numeric(date), data = hd, span = 0.075)
  mod_wet <- loess(wet ~ as.numeric(date), data = hd, span = 0.075)
  mod_water <- loess(water ~ as.numeric(date), data = hd, span = 0.075)
  mod_veg_areas <- loess(veg_areas ~ as.numeric(date), data = hd, span = 0.075)


interpolate_data[[i]] <- new_df_raw %>%
  mutate(Site = site_metadata_sf$Site[i],
         pv = predict(mod_pv, newdata = new_df_raw),
         npv = predict(mod_npv, newdata = new_df_raw),
         bs = predict(mod_bs, newdata = new_df_raw),
         wet = predict(mod_wet, newdata = new_df_raw),
         water = predict(mod_water, newdata = new_df_raw),
         veg_areas = predict(mod_veg_areas, newdata = new_df_raw)) %>%
  mutate(across(.cols = c(pv,npv,bs, wet, water, veg_areas), 
                .fns = ~ case_when(.x > 1 ~ 1, 
                                   .x < 0 ~ 0,
                                   TRUE ~ .x)))

}

interpolate_combined <- bind_rows(interpolate_data) %>%
  mutate(Date = as.Date(date)) %>%
  select(-date)

interpolate_data[[1]] %>%
  ggplot() +
  geom_point(aes(x = date, y = pv)) +
  ylim(c(0,1))
```


```{r precip}
# load in daily precip 
# https://psl.noaa.gov/data/gridded/data.cpc.globalprecip.html
precipitation_daily <- c(terra::rast("data/climate/precip_2022.nc"), terra::rast("data/climate/precip_2023.nc"))
precipitation_daily_df <- bind_cols(site_metadata_sf$Site, 
                                    extract(precipitation_daily, vect(site_metadata_sf)))
colnames(precipitation_daily_df) <- c("Site","ID", as.character(seq.Date(from = as.Date("2022-01-01"), 
                                                     to = as.Date("2023-12-31"), by = "day")))

precipitation_daily_long <- pivot_longer(precipitation_daily_df, cols = 3:732, names_to = "Date", values_to = "Precipitation") %>%
  select(-ID) %>%
  mutate(Date = as.Date(Date)) %>%
  right_join(nights_dep_joined)
```

```{r temp}
# load in daily precip 
# https://psl.noaa.gov/data/gridded/data.cpc.globalprecip.html
tmin_daily <- c(terra::rast("data/climate/tmin_2022.nc"), terra::rast("data/climate/tmin_2023.nc"))
tmin_daily_df <- bind_cols(site_metadata_sf$Site, 
                                    extract(tmin_daily, vect(site_metadata_sf)))
colnames(tmin_daily_df) <- c("Site","ID", as.character(seq.Date(from = as.Date("2022-01-01"), 
                                                     to = as.Date("2023-12-31"), by = "day")))

tmin_daily_long <- pivot_longer(tmin_daily_df, 
                                cols = 3:732, 
                                names_to = "Date", 
                                values_to = "tmin") %>%
  select(-ID) %>%
  mutate(Date = as.Date(Date)) %>%
  right_join(nights_dep_joined)
```

```{r dailyvars}
daily_vars <- left_join(precipitation_daily_long, 
                        tmin_daily_long) %>%
  mutate(Day = lubridate::yday(Date)-243, 
         Day = case_when(Day < 1 ~ Day + 243 + (365-243), 
                         TRUE ~ Day),
         cosDay = 2*pi*Day/365, 
         sinDay = 2*pi*Day/365) %>% 
  left_join(interpolate_combined, by = c("Site", "Date"))
```


# All site records 
```{r}
site_records <- read_csv("data/TLM_2022-23_Barmah-Millewa_FrogsEnsemble1_2023.csv") %>%
  rename(Site_prefix = Site) %>%
  tidyr::separate_wider_delim(cols = "Filename", delim = "/", 
                              names = c(NA,NA,NA,"Site", NA))
```

# Validated site records 

```{r}
site_validation <- read_excel("data/TLM_Barmah-Millewa_2022-23_validations_ALL.xlsx") %>%
 mutate(Site = case_when(Site == "Warri" ~ "Warri Yards", 
                         TRUE ~ Site),
        Site = paste(Site, AM, sep = "_AM"))
```

```{r}
# Generate STAN data 
species_list <- c(`Barking Marsh Frog` = 13059, 
                  `Eastern Sign-bearing Froglet` = 13131,
                  `Common Froglet` = 13134,
                  # `Sloane's Froglet` = 13135,
                  `Peron's Tree Frog` = 13204)#, 
                  # `Pobblebonk Frog` = 63913)
                  # `Growling Grass Frog` = 13207)

nspecies <- length(species_list)

sp_l_col <- paste0("sp_", species_list)

species_cols <- str_extract_all(last(colnames(site_records)), "[-+]?[0-9]+")[[1]] 

#list of species codes and names
class_list<-read_csv("data/ClassList.csv")

#data with column containing string of category probabilities from the AI
names(site_records)[16]<-"probvec"

#clean and split the probabilities
probs <- site_records %>% select(probvec) %>%
  mutate(probvec=str_remove(probvec, "\n")) %>%
  mutate(probvec=str_remove(probvec, "\\[")) %>%
  mutate(probvec=str_remove(probvec, "\\]")) %>%
  mutate(probvec=str_squish(probvec)) %>%
  separate(probvec, into=paste0("sp_",class_list$TaxonId), sep="\\s") %>%
  mutate(across(`sp_-2`:`sp_525739`, as.numeric))

# perons probs 
frog_probs <- probs %>%
  dplyr::select(all_of(sp_l_col))

site_records_date <- site_records %>% 
  mutate(Date = as.Date(Date_evening_of, "%d/%m/%Y"), 
         DateTime = as.POSIXct(paste(Date, Time))) %>%
  bind_cols(frog_probs)

# joined data
joined_data <- list()

# indexes for species
nsites <- length(site_metadata_sf$Site)
empty_array <- array(dim = c(nsites, length(species_list)))
start_idx_0 <- empty_array
end_idx_0 <- empty_array
start_idx_1 <- empty_array
end_idx_1 <- empty_array
start_idx_2 <- empty_array
end_idx_2 <- empty_array
any_seen <- empty_array
site_idx_start <- empty_array
site_idx_end <- empty_array

call_rate_matrix <- list()

for(i in 1:length(species_list)) {

all_records_filt <- site_records_date %>%
  group_by(Site, Date) %>%
  summarise(Prob_One = max(!!sym(sp_l_col[i])), 
            FileId = FileId[which(!!sym(sp_l_col[i]) == max(!!sym(sp_l_col[i])))], 
            Orig_Start_Time = Orig_Start_Time[which(!!sym(sp_l_col[i]) == max(!!sym(sp_l_col[i])))], 
            Orig_End_Time = Orig_End_Time[which(!!sym(sp_l_col[i]) == max(!!sym(sp_l_col[i])))]) %>%
  slice(1) %>%
  ungroup()

validation_records_clean <- site_validation %>% 
  filter(!str_detect(Validation_TaxonIDs, ";") & Predict_TaxonId == species_list[i]) %>%
  select(FileId, Orig_Start_Time, Orig_End_Time, Site, Detected = !!sym(names(species_list)[i])) %>%
  left_join(site_records_date %>%
              select(FileId, Orig_Start_Time, Orig_End_Time, Site, Date, Prob_One = !!sym(sp_l_col[i])))

joined_data[[i]] <- full_join(all_records_filt, validation_records_clean) %>%
  group_by(Site, Date) %>%
  arrange(desc(Detected), desc(Prob_One)) %>%
  # arrange(desc(Prob_One)) %>%
  slice(1) %>%
  ungroup() %>%
  right_join(daily_vars) %>%
  mutate(Detected = replace_na(Detected, -2), 
         Prob_One = replace_na(Prob_One, 0)) %>%
  mutate(Detected = abs(Detected), 
         Site_f = as.integer(factor(Site)), 
         Prob_f = case_when(Prob_One == 1 ~ 0.999, 
                                Prob_One == 0 ~ 0.001, 
                                TRUE ~ Prob_One),
         Prob_One_M = qlogis(Prob_f)) %>%
  group_by(Site_f) %>%
  mutate(any_seen = case_when(any(Detected == 1) ~ 1, 
                              TRUE ~ 0)) %>%
  ungroup() %>%
  arrange(Site_f, Detected) 

# Daily precipitation matrix
theta_form <- ~ scale(Precipitation) + scale(tmin) + scale(wet) + scale(water) + scale(pv) + cosDay + sinDay
call_rate_matrix[[i]] <- model.matrix(theta_form, data = joined_data[[i]])

for(j in 1:nsites) {
  start_idx_0[j,i] <- min(which(joined_data[[i]]$Site_f == j & joined_data[[i]]$Detected == 0))
  end_idx_0[j,i] <- max(which(joined_data[[i]]$Site_f == j & joined_data[[i]]$Detected == 0))
  
  start_idx_1[j,i] <- min(which(joined_data[[i]]$Site_f == j & joined_data[[i]]$Detected == 1))
  end_idx_1[j,i] <- max(which(joined_data[[i]]$Site_f == j & joined_data[[i]]$Detected == 1))
  
  start_idx_2[j,i] <- min(which(joined_data[[i]]$Site_f == j & joined_data[[i]]$Detected == 2))
  end_idx_2[j,i] <- max(which(joined_data[[i]]$Site_f == j & joined_data[[i]]$Detected == 2))
    
  site_idx_start[j,i] <- min(which(joined_data[[i]]$Site_f == j))
  site_idx_end[j,i] <- max(which(joined_data[[i]]$Site_f == j))
}

start_idx_0[is.infinite(start_idx_0[,i]),i] <- 0
start_idx_1[is.infinite(start_idx_1[,i]),i] <- 0
start_idx_2[is.infinite(start_idx_2[,i]),i] <- 0

end_idx_0[is.infinite(end_idx_0[,i]),i] <- 0
end_idx_1[is.infinite(end_idx_1[,i]),i] <- 0
end_idx_2[is.infinite(end_idx_2[,i]),i] <- 0

any_seen[,i] <- as.integer(start_idx_1[,i] != 0)
}
```


```{r}
nfiles <- nrow(joined_data[[1]])
scores <- lapply(joined_data, function(x) pull(x, Prob_f)) 
site_list <- lapply(joined_data, function(x) pull(x, Site_f)) 

stan_data <- list(nfiles = nfiles, 
                  nsites = nsites, 
                  nspec = nspecies,
                  score = array(unlist(scores),dim=c(nfiles,nspecies)), 
                  site_idx_start = site_idx_start, 
                  site_idx_end = site_idx_end,
                  start_idx_0 = start_idx_0, 
                  end_idx_0 = end_idx_0,
                  start_idx_1 = start_idx_1, 
                  end_idx_1 = end_idx_1, 
                  start_idx_2 = start_idx_2, 
                  end_idx_2 = end_idx_2, 
                  any_seen = any_seen, 
                  theta_mm = call_rate_matrix, 
                  theta_nc = ncol(call_rate_matrix[[1]]))

saveRDS(stan_data, "data/stan_data.rds")

```


```{r}
cont_model <- cmdstan_model("stan/continuous_model.stan")
cont_model_ms <- cmdstan_model("stan/continuous_model_ms.stan")
cont_model_ms_beta <- cmdstan_model("stan/continuous_model_ms_beta.stan")
```

```{r modelparams}
ni <- 500 #samples
nw <- 500 #warmups
nc <- 8 #chains
```

```{r}
# fit <- cont_model_ms$sample(data = stan_data,
#                          chains = nc,
#                          parallel_chains = nc,
#                          show_messages = TRUE,
#                          save_warmup = FALSE,
#                          iter_sampling = ni,
#                          iter_warmup = nw, adapt_delta = 0.95)

fit <- cont_model_ms_beta$sample(data = stan_data,
                         chains = nc,
                         parallel_chains = nc,
                         show_messages = TRUE,
                         save_warmup = FALSE,
                         iter_sampling = ni,
                         iter_warmup = nw, adapt_delta = 0.95)
```

```{r}
psi_summary <- fit$summary("psi")
psi_summary_sp <- list()
for(i in 1:nspecies) {
  var_names <- paste0("psi[",1:nsites, ",", i, "]")
  psi_summary_sp[[i]] <- psi_summary %>% 
    filter(variable %in% var_names) %>%
    mutate(species = names(species_list)[i], 
           any_seen = stan_data$any_seen[,i])
}
psi_summary <- bind_rows(psi_summary_sp)

psi_summary %>%
  group_by(any_seen, species) %>%
  summarise(psi = mean(mean))
```

```{r}
# phenology summary 
theta_phen <- fit$summary("theta_phen") 

theta_phen_spec <- list()

for(i in 1:nspecies) {
  theta_phen_spec[[i]] <- theta_phen %>%
  filter(str_detect(variable, paste0(",",i,"]"))) %>%
    mutate(Species = names(species_list)[i], 
           Day = 1:365, 
           Date = seq.Date(from = as.Date("2022-09-01"), to = as.Date("2023-08-30"), length.out = 365))
}

theta_phen_joined <- bind_rows(theta_phen_spec)

theta_phen_joined %>% ggplot(aes(x = Day, 
                                 y = mean, 
                                 colour = Species)) +
  geom_line() +
  scale_x_continuous(limits = c(min(daily_vars$Day), max(daily_vars$Day)))
```

```{r}
nbeta_theta <- ncol(call_rate_matrix[[1]])
beta_theta_names <- labels(call_rate_matrix[[1]])[[2]]
theta_summary <- fit$summary("beta_theta")
theta_summary_sp <- list()
for(i in 1:nspecies) {
  var_names <- paste0("beta_theta[",i, ",", 1:nbeta_theta, "]")
  theta_summary_sp[[i]] <- theta_summary %>% 
    filter(variable %in% var_names) %>%
    mutate(species = names(species_list)[i], 
           param = beta_theta_names)
}
theta_summary_combined <- bind_rows(theta_summary_sp)


theta_summary_combined %>% 
  ggplot(aes(x = param, y = mean, colour = species)) +
  geom_pointrange(aes(ymin = q5, ymax = q95), position = position_dodge2(width = 0.5, padding = 0.5))
```

```{r}
mu_summary <- fit$draws("mu_pred")
mcmc_areas(mu_summary, prob_outer = 0.9)
```

